docker builds for linux32 (#51)
* docker builds for linux32

* job names may only contain alphanumeric characters and _ and may not start with a number

* the input device is not a TTY

* install build-essential

* also git

* sudo not found

* switch to buster and install libssl-dev

* touch for ci

* tested locally; should pass on CI

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -11,7 +11,7 @@ variables:
   PY_ARCH: x64
 
 jobs:
-- job: Build
+- job: host_build
   strategy:
     matrix:
       Linux:
@@ -168,8 +168,140 @@ jobs:
       pathtoPublish: dist
       artifactName: dist
 
-- job: Release
-  dependsOn: Build
+- job: docker_build
+  strategy:
+    matrix:
+      Linux-32:
+        vmImage: ubuntu-16.04
+        dockerImage: i386/python:3.6-slim-buster
+  pool:
+    vmImage: $(vmImage)
+  steps:
+  - task: Bash@3
+    displayName: Create and start & prepare container
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        CID=$(docker create -t -w /tmp/wrk -v $PWD:/tmp/src:ro $(dockerImage) sleep infinity)
+        echo "##vso[task.setvariable variable=CID]$CID"
+        docker start $CID
+        docker exec -i $CID bash -c "\
+          cp -r /tmp/src/. . && \
+          apt-get update && \
+          apt-get install -y build-essential git libssl-dev zip"
+  - task: Bash@3
+    displayName: Install development requirements and restore WGPU native binary
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        docker exec -i $CID bash -c "\
+          python -m pip install -U pip && \
+          pip install -U -r dev-requirements.txt && \
+          python download-wgpu-native.py"
+  - task: Bash@3
+    displayName: Build wheel and install in development mode
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        docker exec -i $CID bash -c "\
+          python setup.py develop && \
+          python setup.py bdist_wheel"
+  - task: Bash@3
+    displayName: Test
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        docker exec -i $CID bash -c "\
+          pytest --junit-xml=results.xml || true"
+        docker cp $CID:/tmp/wrk/results.xml .
+
+        # Fail the task if results.xml was not created
+        if [[ ! -f results.xml ]]
+        then
+          echo "##vso[task.logissue type=error]No test results were found"
+          exit 1
+        fi
+  - task: PublishTestResults@2
+    inputs:
+      testResultsFiles: results.xml
+      mergeTestResults: true
+      failTaskOnFailedTests: true
+      testRunTitle: Test $(vmImage) (docker)
+  - task: Bash@3
+    displayName: Manylinux1 tag
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        docker exec -i $CID bash -c "\
+          apt-get install -y patchelf && \
+          auditwheel repair dist/*.whl && \
+          rm dist/*.whl && \
+          cp wheelhouse/*.whl dist/."
+        mkdir -p dist
+        docker cp $CID:/tmp/wrk/dist/. dist/.
+  - task: Bash@3
+    displayName: Test wheel
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        docker exec -i $CID bash -c "\
+          python setup.py develop --uninstall && \
+          python setup.py clean --all && \
+          rm -rf ./wgpu && \
+          mkdir -p /tmp/test && \
+          pushd /tmp/test && \
+          pip install /tmp/wrk/dist/*.whl && \
+          popd && \
+          pytest --junit-xml=results-wheel.xml || true && \
+          pip uninstall -y wgpu && \
+          git reset --hard HEAD"
+        docker cp $CID:/tmp/wrk/results-wheel.xml .
+
+        # Fail the task if results-wheel.xml was not created
+        if [[ ! -f results-wheel.xml ]]
+        then
+          echo "##vso[task.logissue type=error]No test results were found"
+          exit 1
+        fi
+  - task: PublishTestResults@2
+    inputs:
+      testResultsFiles: results-wheel.xml
+      mergeTestResults: true
+      failTaskOnFailedTests: true
+      testRunTitle: Test $(vmImage) (wheel, docker)
+  - task: Bash@3
+    displayName: Twine check
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        docker exec -i $CID bash -c "\
+          twine check dist/*"
+  - task: PublishBuildArtifacts@1
+    displayName: Publish distributions
+    inputs:
+      pathtoPublish: dist
+      artifactName: dist        
+  - task: Bash@3
+    displayName: 'Post-job: Stop and remove container'
+    condition: and(always(), ne(variables['CID'], ''))
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        docker stop $CID
+        docker rm $CID
+
+- job: release
+  dependsOn:
+  - host_build
+  - docker_build
   condition: and(succeeded(), ne(variables['Build.Reason'], 'PullRequest'))
   pool:
     vmImage: ubuntu-16.04
