indentation fix

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -24,33 +24,33 @@ jobs:
     inputs:
       targetType: inline
       script: |
-      python -m pip install -U pip setuptools wheel
-      pip install -r dev-requirements.txt
+        python -m pip install -U pip setuptools wheel
+        pip install -r dev-requirements.txt
   - task: Bash@3
     displayName: Lint
     inputs:
       targetType: inline
       script: |
-      black --check
+        black --check
   - task: Bash@3
     displayName: Build wheel and install in development mode
     inputs:
       targetType: inline
       script: |
-      python setup.py bdist_wheel develop
+        python setup.py bdist_wheel develop
   - task: Bash@3
     displayName: Test
     inputs:
       targetType: inline
       script: |
-      pipenv run pytest --disable-warnings --junit-xml=results.xml || true
+        pipenv run pytest --disable-warnings --junit-xml=results.xml || true
 
-      # Fail the task if results.xml was not created
-      if [[ ! -f results.xml ]]
-      then
-        echo "##vso[task.logissue type=error]No test results were found"
-        exit 1
-      fi
+        # Fail the task if results.xml was not created
+        if [[ ! -f results.xml ]]
+        then
+          echo "##vso[task.logissue type=error]No test results were found"
+          exit 1
+        fi
   - task: PublishTestResults@2
     inputs:
       testResultsFiles: results.xml
@@ -62,12 +62,12 @@ jobs:
     inputs:
       targetType: inline
       script: |
-      python setup.py develop --uninstall
-      mkdir ../pkgtest
-      cp dist/*.whl ../pkgtest/.
-      cd ../pkgtest
-      pip install *.whl
-      python -c "import wgpu"
+        python setup.py develop --uninstall
+        mkdir ../pkgtest
+        cp dist/*.whl ../pkgtest/.
+        cd ../pkgtest
+        pip install *.whl
+        python -c "import wgpu"
   - task: PublishBuildArtifacts@1
     displayName: Publish package artifact
     inputs:
