CI sdist and manylinux1 support (#39)
* wip

* properly support sdist

* and manylinux1

* missed one

* cross platform tmpdir

* typo

* need to use abs path

* sigh. pathseps.

* bash

* pin wheel in order not to break auditwheel

* force unix path

* different approach

* dont fail if it doesn exist

* only swap to manylinux1 wheel on success

* dont upload generic linux wheels to pypi

* typo

* install patchelf, required by auditwheel

* run twine check in CI

* avoid malformed PKG-INFO

diff --git a/azure-pipelines.yml b/azure-pipelines.yml
--- a/azure-pipelines.yml
+++ b/azure-pipelines.yml
@@ -11,6 +11,8 @@ jobs:
     matrix:
       Linux:
         vmImage: ubuntu-16.04
+        SDIST: 1
+        LINT: 1
       MacOS:
         vmImage: macOS-10.14
         MACOSX_DEPLOYMENT_TARGET: '10.13'
@@ -32,14 +34,16 @@ jobs:
         python -m pip install -U pip
         pip install -U -r dev-requirements.txt
   - task: Bash@3
-    displayName: Restore WGPU native binary
+    displayName: Create source distribution
+    condition: and(succeeded(), eq(variables['SDIST'], '1'))
     inputs:
       targetType: inline
       script: |
         set -ex
-        python download-wgpu-native.py
+        python setup.py sdist
   - task: Bash@3
     displayName: Lint (black)
+    condition: and(succeeded(), eq(variables['LINT'], '1'))
     inputs:
       targetType: inline
       script: |
@@ -47,11 +51,19 @@ jobs:
         black --check .
   - task: Bash@3
     displayName: Lint (flake8)
+    condition: and(succeeded(), eq(variables['LINT'], '1'))
     inputs:
       targetType: inline
       script: |
         set -ex
         flake8
+  - task: Bash@3
+    displayName: Restore WGPU native binary
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        python download-wgpu-native.py
   - task: Bash@3
     displayName: Build wheel and install in development mode
     inputs:
@@ -59,14 +71,14 @@ jobs:
       script: |
         set -ex
         python setup.py develop
-        python setup.py sdist bdist_wheel
+        python setup.py bdist_wheel
   - task: Bash@3
     displayName: Test
     inputs:
       targetType: inline
       script: |
         set -ex
-        pytest --disable-warnings --junit-xml=results.xml || true
+        pytest --junit-xml=results.xml || true
 
         # Fail the task if results.xml was not created
         if [[ ! -f results.xml ]]
@@ -81,33 +93,72 @@ jobs:
       failTaskOnFailedTests: true
       testRunTitle: Test $(vmImage)
   - task: Bash@3
-    displayName: Test (packaged)
+    displayName: Test wheel
     inputs:
       targetType: inline
       script: |
         set -ex
         python setup.py develop --uninstall
-        rm -rf ./wgpu ./build ./egg-info
-        pip install dist/*.whl
-        pytest --disable-warnings --junit-xml=results-packaged.xml || true
+        python setup.py clean --all
+        rm -rf ./wgpu
+        pushd $AGENT_TEMPDIRECTORY
+        pip install $(echo "$(Build.SourcesDirectory)" | sed -e 's/\\/\//g')/dist/*.whl
+        popd
+        pytest --junit-xml=results-wheel.xml || true
+        pip uninstall -y wgpu
+        git restore ./wgpu
 
-        # Fail the task if results-packaged.xml was not created
-        if [[ ! -f results-packaged.xml ]]
+        # Fail the task if results-wheel.xml was not created
+        if [[ ! -f results-wheel.xml ]]
         then
           echo "##vso[task.logissue type=error]No test results were found"
           exit 1
         fi
   - task: PublishTestResults@2
     inputs:
-      testResultsFiles: results-packaged.xml
+      testResultsFiles: results-wheel.xml
       mergeTestResults: true
       failTaskOnFailedTests: true
-      testRunTitle: Test $(vmImage) (packaged)
+      testRunTitle: Test $(vmImage) (wheel)
+  - task: Bash@3
+    displayName: Test sdist
+    condition: and(succeeded(), eq(variables['SDIST'], '1'))
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        rm -rf ./wgpu
+        pushd $AGENT_TEMPDIRECTORY
+        pip install $(echo "$(Build.SourcesDirectory)" | sed -e 's/\\/\//g')/dist/*.tar.gz
+        popd
+        # don't run tests, we just want to know if the sdist can be installed
+        pip uninstall -y wgpu
+        git restore ./wgpu
+  - task: Bash@3
+    displayName: Manylinux1 tag
+    condition: and(succeeded(), eq(variables['Agent.OS'], 'Linux'))
+    continueOnError: true
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        sudo apt-get update
+        sudo apt-get install -y patchelf
+        auditwheel repair dist/*.whl
+        rm dist/*.whl
+        cp wheelhouse/*.whl dist/.
+  - task: Bash@3
+    displayName: Twine check
+    inputs:
+      targetType: inline
+      script: |
+        set -ex
+        twine check dist/*
   - task: PublishBuildArtifacts@1
-    displayName: Publish wheels
+    displayName: Publish distributions
     inputs:
       pathtoPublish: dist
-      artifactName: wheels
+      artifactName: dist
 
 - job: Release
   dependsOn: Build
@@ -128,10 +179,10 @@ jobs:
         TAGS=$(git describe --tags)
         echo "##vso[task.setvariable variable=TAGS]$TAGS"
   - task: DownloadBuildArtifacts@0
-    displayName: Download wheels
+    displayName: Download dist
     condition: and(succeeded(), ne(variables['TAGS'], ''))
     inputs:
-      artifactName: wheels
+      artifactName: dist
       downloadPath: .
   - task: GithubRelease@1
     displayName: GitHub Release
@@ -139,7 +190,9 @@ jobs:
     inputs:
       gitHubConnection: github.com_almarklein
       repositoryName: 'almarklein/wgpu-py'
-      assets: 'wheels/*.whl'
+      assets: |
+        dist/*.whl
+        dist/*.tar.gz
       isDraft: true
       addChangeLog: false
       assetUploadMode: replace
@@ -158,11 +211,11 @@ jobs:
     inputs:
       pythonUploadServiceConnection: pypi
   - task: Bash@3
-    displayName: Upload wheels to PyPI
+    displayName: Upload dist to PyPI
     condition: and(succeeded(), ne(variables['TAGS'], ''))
     inputs:
       targetType: inline
       script: |
         set -ex
-        rm wheels/*linux*.whl
-        twine upload -r "wgpu" --config-file $(PYPIRC_PATH) --non-interactive wheels/*
+        rm dist/*linux*.whl  # TODO: ensure manylinux1 platform tag
+        twine upload -r "wgpu" --config-file $(PYPIRC_PATH) --non-interactive dist/*
